# Generated by Django 5.0.7 on 2024-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
