# Generated by Django 5.0.4 on 2024-07-03 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('long_description', models.TextField()),
                ('features', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('image_one', models.ImageField(upload_to='projects/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory')),
            ],
        ),
    ]
