# Generated by Django 5.0.4 on 2024-07-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfeatures_remove_project_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Applications',
            field=models.ManyToManyField(to='projects.projectapplications'),
        ),
    ]
