# Generated by Django 5.0 on 2024-07-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_steps_alter_blogtable_image_blogtable_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtable',
            name='process',
            field=models.ManyToManyField(to='BlogApp.steps'),
        ),
    ]
