# Generated by Django 5.0 on 2024-07-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_blogtable_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='author',
            field=models.CharField(default='codeAj', max_length=255),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
