# Generated by Django 5.0.4 on 2024-07-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_process/')),
                ('title', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('long_description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('slug', models.SlugField(unique=True)),
                ('process', models.ManyToManyField(to='services.serviceprocess')),
            ],
        ),
    ]
