# Generated by Django 5.0 on 2024-07-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_title',
            field=models.CharField(max_length=555),
        ),
    ]
