# Generated by Django 5.0.4 on 2024-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_service_name_alter_service_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprocess',
            name='bottom_tag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='serviceprocess',
            name='top_tag',
            field=models.TextField(default=''),
        ),
    ]
